In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression , ElasticNet, LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler,PolynomialFeatures,LabelEncoder
from sklearn.metrics import r2_score, mean_squared_error,confusion_matrix,accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.compose import make_column_selector
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold , cross_val_score
from sklearn.impute import SimpleImputer

In [2]:
iris = pd.read_csv('iris.csv')

In [3]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
iris.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [5]:
y = iris['Species']
X = iris.drop('Species',axis=1)

In [6]:
X.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width'], dtype='object')

In [7]:
y.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [8]:
lbl = LabelEncoder()

In [9]:
X_train , X_test , y_train , y_test = train_test_split(X,y,random_state=24,test_size=0.3)

In [10]:
lbl = LabelEncoder()
iris['Species'] = lbl.fit_transform(iris['Species'])

In [11]:
lbl.classes_

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [12]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
pd.crosstab(y_test,y_pred) 

col_0       setosa  versicolor  virginica
Species                                  
setosa          15           0          0
versicolor       0          11          1
virginica        0           0         18

In [13]:
print(confusion_matrix(y_test,y_pred))

[[15  0  0]
 [ 0 11  1]
 [ 0  0 18]]


In [14]:
accuracy_score(y_test,y_pred)

0.9777777777777777

##### Naive Rule/BaseLine Model

In [15]:
y_pred = np.zeros(y_test.shape[0])

In [16]:
y_test.value_counts()

Species
virginica     18
setosa        15
versicolor    12
Name: count, dtype: int64

In [17]:
accuracy_score(y_test,y_pred)

0.0