In [1]:
import numpy as np

In [2]:
a = np.array([90,34,89,23,50,120,67])
b = np.array([1,3,4,2,5,2,3])

In [3]:
ma , mb = a.mean() , b.mean()

In [4]:
sa , sb = a.std() , b.std()

In [8]:
# standard scaling
# independent identical distributed variables
scl_a = (a-ma)/sa
scl_b = (b-mb)/sb

In [9]:
(ma,sa),(scl_a.mean(),scl_b.std())

((67.57142857142857, 31.923377653630677), (7.335402126987641e-17, 1.0))

In [10]:
(mb,sb),(scl_b.mean(),scl_b.std())

((2.857142857142857, 1.2453996981544782), (-8.921435019309294e-17, 1.0))

In [11]:
scl_a

array([ 0.70257514, -1.05162521,  0.67125013, -1.39620027, -0.55042511,
        1.64232532, -0.0179    ])

In [12]:
scl_b

array([-1.49120227,  0.11470787,  0.91766294, -0.6882472 ,  1.720618  ,
       -0.6882472 ,  0.11470787])

#### Using StandardScaler()

In [13]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [15]:
scl_std = StandardScaler()
df = pd.DataFrame({'a':a,'b':b})
scl_std.fit(df)

StandardScaler()

In [18]:
print(scl_std.mean_)
print(ma , mb)

[67.57142857  2.85714286]
67.57142857142857 2.857142857142857


In [20]:
print(scl_std.scale_)
print(sa,sb)

[31.92337765  1.2453997 ]
31.923377653630677 1.2453996981544782


In [23]:
scl_std.var_  # std

array([1019.10204082,    1.55102041])

#### MinMax Scaling (Scales value betweeen o to 1)

In [24]:
a,b

(array([ 90,  34,  89,  23,  50, 120,  67]), array([1, 3, 4, 2, 5, 2, 3]))

In [25]:
mn_a,mn_b,mx_a,mx_b = a.min(),b.min(),a.max(),b.max()

In [27]:
print(mn_a,mn_b,mx_a,mx_b)

23 1 120 5


In [28]:
scl_a = (a-mn_a) / (mx_a-mn_a)
scl_a

array([0.69072165, 0.11340206, 0.68041237, 0.        , 0.27835052,
       1.        , 0.45360825])

In [30]:
scl_b = (b-mn_b) / (mx_b-mn_b)
scl_b

array([0.  , 0.5 , 0.75, 0.25, 1.  , 0.25, 0.5 ])